---

provisioner:
  name: chef_zero
  roles_path: ../../roles
  data_bags_path: ../../data_bags
  environments_path: ../../environments
  cookbook_path: ../../cookbooks
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: plex-server
    run_list:
      - recipe[plex-hackday::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes: { plex_role: "server" }

  - name: plex-client
    run_list:
      - recipe[plex-hackday::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes: { plex_role: "client" }